CREATE DATABASE to_do_app;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS tasks (
  id UUID NOT NULL UNIQUE DEFAULT UUID_generate_v4(),
  title VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  done BOOLEAN DEFAULT FALSE,
  create_date TIMESTAMP DEFAULT NOW()
);
